/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */
#ifdef HAVE_ORB_ORBIT_H
#include <string.h>
#include "ajcorbaembl.h"

#if ( (TC_IMPL_TC_GNOME_Unknown_0 == 'B') \
&& (TC_IMPL_TC_GNOME_Unknown_1 == 'i') \
&& (TC_IMPL_TC_GNOME_Unknown_2 == 'o') \
&& (TC_IMPL_TC_GNOME_Unknown_3 == 'C') \
&& (TC_IMPL_TC_GNOME_Unknown_4 == 'o') \
&& (TC_IMPL_TC_GNOME_Unknown_5 == 'r') \
&& (TC_IMPL_TC_GNOME_Unknown_6 == 'b') \
&& (TC_IMPL_TC_GNOME_Unknown_7 == 'a') \
&& (TC_IMPL_TC_GNOME_Unknown_8 == '_') \
&& (TC_IMPL_TC_GNOME_Unknown_9 == '0') \
&& (TC_IMPL_TC_GNOME_Unknown_10 == '_') \
&& (TC_IMPL_TC_GNOME_Unknown_11 == '2') \
) && !defined(TC_DEF_TC_GNOME_Unknown)
#define TC_DEF_TC_GNOME_Unknown 1
const struct CORBA_TypeCode_struct TC_GNOME_Unknown_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Unknown", "IDL:GNOME/Unknown:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_RequestTooLarge_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_RequestTooLarge_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_RequestTooLarge_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_RequestTooLarge_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_RequestTooLarge_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_RequestTooLarge_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_RequestTooLarge_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_RequestTooLarge_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_RequestTooLarge_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_RequestTooLarge_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_RequestTooLarge_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_RequestTooLarge_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_RequestTooLarge)
#define TC_DEF_TC_org_biocorba_seqcore_RequestTooLarge 1
static const char *anon_subnames_array5[] = { "reason", "suggested_size" };
static const CORBA_TypeCode anon_subtypes_array6[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
      (CORBA_TypeCode) & TC_CORBA_long_struct };
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_RequestTooLarge_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "RequestTooLarge",
      "IDL:org/biocorba/seqcore/RequestTooLarge:1.0",
   0, 2,
   (const char **) anon_subnames_array5,
   (CORBA_TypeCode *) anon_subtypes_array6,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_OutOfRange_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_OutOfRange_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_OutOfRange_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_OutOfRange_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_OutOfRange_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_OutOfRange_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_OutOfRange_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_OutOfRange_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_OutOfRange_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_OutOfRange_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_OutOfRange_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_OutOfRange_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_OutOfRange)
#define TC_DEF_TC_org_biocorba_seqcore_OutOfRange 1
static const char *anon_subnames_array9[] = { "reason" };
static const CORBA_TypeCode anon_subtypes_array10[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_OutOfRange_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_except, "OutOfRange", "IDL:org/biocorba/seqcore/OutOfRange:1.0",
   0, 1,
   (const char **) anon_subnames_array9,
   (CORBA_TypeCode *) anon_subtypes_array10,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_EndOfStream_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_EndOfStream_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_EndOfStream_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_EndOfStream_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_EndOfStream_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_EndOfStream_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_EndOfStream_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_EndOfStream_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_EndOfStream_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_EndOfStream_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_EndOfStream_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_EndOfStream_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_EndOfStream)
#define TC_DEF_TC_org_biocorba_seqcore_EndOfStream 1
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_EndOfStream_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "EndOfStream", "IDL:org/biocorba/seqcore/EndOfStream:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_NeedsUpdate_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NeedsUpdate_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NeedsUpdate_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NeedsUpdate_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NeedsUpdate_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NeedsUpdate_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NeedsUpdate_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NeedsUpdate_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NeedsUpdate_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NeedsUpdate_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NeedsUpdate_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NeedsUpdate_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_NeedsUpdate)
#define TC_DEF_TC_org_biocorba_seqcore_NeedsUpdate 1
static const char *anon_subnames_array17[] = { "reason" };
static const CORBA_TypeCode anon_subtypes_array18[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_NeedsUpdate_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "NeedsUpdate", "IDL:org/biocorba/seqcore/NeedsUpdate:1.0",
   0, 1,
   (const char **) anon_subnames_array17,
   (CORBA_TypeCode *) anon_subtypes_array18,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_DoesNotExist_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_DoesNotExist_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_DoesNotExist_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_DoesNotExist_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_DoesNotExist_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_DoesNotExist_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_DoesNotExist_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_DoesNotExist_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_DoesNotExist_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_DoesNotExist_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_DoesNotExist_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_DoesNotExist_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_DoesNotExist)
#define TC_DEF_TC_org_biocorba_seqcore_DoesNotExist 1
static const char *anon_subnames_array21[] = { "reason" };
static const CORBA_TypeCode anon_subtypes_array22[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_DoesNotExist_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "DoesNotExist",
      "IDL:org/biocorba/seqcore/DoesNotExist:1.0",
   0, 1,
   (const char **) anon_subnames_array21,
   (CORBA_TypeCode *) anon_subtypes_array22,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_UnableToProcess_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UnableToProcess_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UnableToProcess_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UnableToProcess_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UnableToProcess_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UnableToProcess_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UnableToProcess_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UnableToProcess_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UnableToProcess_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UnableToProcess_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UnableToProcess_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UnableToProcess_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_UnableToProcess)
#define TC_DEF_TC_org_biocorba_seqcore_UnableToProcess 1
static const char *anon_subnames_array25[] = { "reason" };
static const CORBA_TypeCode anon_subtypes_array26[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_UnableToProcess_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_except, "UnableToProcess",
      "IDL:org/biocorba/seqcore/UnableToProcess:1.0",
   0, 1,
   (const char **) anon_subnames_array25,
   (CORBA_TypeCode *) anon_subtypes_array26,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'b') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_10 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_11 == '2') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array30[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array30,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'b') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_10 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_11 == '2') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array39[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array39,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_StringList_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_StringList_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_StringList_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_StringList_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_StringList_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_StringList_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_StringList_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_StringList_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_StringList_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_StringList_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_StringList_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_StringList_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_StringList)
#define TC_DEF_TC_org_biocorba_seqcore_StringList 1
static const CORBA_TypeCode anon_subtypes_array43[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_string_struct };
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_StringList_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "StringList", "IDL:org/biocorba/seqcore/StringList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array43,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_long_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_1 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_3 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_4 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_6 == 'b') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_9 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_10 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_11 == '2') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_long)
#define TC_DEF_TC_CORBA_sequence_CORBA_long 1
static const CORBA_TypeCode anon_subtypes_array47[] =
   { (CORBA_TypeCode) & TC_CORBA_long_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_long_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array47,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_long_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_1 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_3 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_4 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_6 == 'b') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_9 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_10 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_long_11 == '2') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_long)
#define TC_DEF_TC_CORBA_sequence_CORBA_long 1
static const CORBA_TypeCode anon_subtypes_array56[] =
   { (CORBA_TypeCode) & TC_CORBA_long_struct };
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_long_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array56,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_LongList_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_LongList_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_LongList_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_LongList_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_LongList_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_LongList_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_LongList_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_LongList_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_LongList_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_LongList_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_LongList_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_LongList_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_LongList)
#define TC_DEF_TC_org_biocorba_seqcore_LongList 1
static const CORBA_TypeCode anon_subtypes_array60[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_long_struct };
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_LongList_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "LongList", "IDL:org/biocorba/seqcore/LongList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array60,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_NameValueSet_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSet_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSet_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSet_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSet_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSet_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSet_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSet_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSet_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSet_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSet_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSet_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_NameValueSet)
#define TC_DEF_TC_org_biocorba_seqcore_NameValueSet 1
static const char *anon_subnames_array63[] = { "name", "values" };
static const CORBA_TypeCode anon_subtypes_array64[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
      (CORBA_TypeCode) & TC_org_biocorba_seqcore_StringList_struct };
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_NameValueSet_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_struct, "NameValueSet",
      "IDL:org/biocorba/seqcore/NameValueSet:1.0",
   0, 2,
   (const char **) anon_subnames_array63,
   (CORBA_TypeCode *) anon_subtypes_array64,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_1 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_3 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_4 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_6 == 'b') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_9 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_10 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_11 == '2') \
) && !defined(TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet)
#define TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet 1
static const CORBA_TypeCode anon_subtypes_array68[] =
   { (CORBA_TypeCode) & TC_org_biocorba_seqcore_NameValueSet_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array68,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_1 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_3 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_4 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_6 == 'b') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_9 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_10 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_11 == '2') \
) && !defined(TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet)
#define TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet 1
static const CORBA_TypeCode anon_subtypes_array77[] =
   { (CORBA_TypeCode) & TC_org_biocorba_seqcore_NameValueSet_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array77,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_NameValueSetList_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSetList_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSetList_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSetList_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSetList_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSetList_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSetList_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSetList_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSetList_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSetList_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSetList_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_NameValueSetList_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_NameValueSetList)
#define TC_DEF_TC_org_biocorba_seqcore_NameValueSetList 1
static const CORBA_TypeCode anon_subtypes_array81[] =
   { (CORBA_TypeCode) &

TC_CORBA_sequence_org_biocorba_seqcore_NameValueSet_struct };
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_NameValueSetList_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "NameValueSetList",
      "IDL:org/biocorba/seqcore/NameValueSetList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array81,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_SeqType_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqType_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqType_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqType_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqType_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqType_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqType_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqType_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqType_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqType_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqType_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqType_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_SeqType)
#define TC_DEF_TC_org_biocorba_seqcore_SeqType 1
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_SeqType_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "SeqType", "IDL:org/biocorba/seqcore/SeqType:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_AnonymousSeq_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_AnonymousSeq_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_AnonymousSeq_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_AnonymousSeq_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_AnonymousSeq_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_AnonymousSeq_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_AnonymousSeq_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_AnonymousSeq_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_AnonymousSeq_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_AnonymousSeq_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_AnonymousSeq_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_AnonymousSeq_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_AnonymousSeq)
#define TC_DEF_TC_org_biocorba_seqcore_AnonymousSeq 1
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_AnonymousSeq_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "AnonymousSeq",
      "IDL:org/biocorba/seqcore/AnonymousSeq:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeq_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeq_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeq_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeq_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeq_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeq_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeq_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeq_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeq_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeq_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeq_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeq_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_PrimarySeq)
#define TC_DEF_TC_org_biocorba_seqcore_PrimarySeq 1
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_PrimarySeq_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "PrimarySeq", "IDL:org/biocorba/seqcore/PrimarySeq:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_1 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_3 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_4 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_6 == 'b') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_9 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_10 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_11 == '2') \
) && !defined(TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq)
#define TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq 1
static const CORBA_TypeCode anon_subtypes_array97[] =
   { (CORBA_TypeCode) & TC_Object_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array97,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_1 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_3 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_4 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_6 == 'b') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_9 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_10 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_11 == '2') \
) && !defined(TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq)
#define TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq 1
static const CORBA_TypeCode anon_subtypes_array106[] =
   { (CORBA_TypeCode) & TC_Object_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array106,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqList_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqList_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqList_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqList_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqList_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqList_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqList_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqList_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqList_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqList_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqList_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqList_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_PrimarySeqList)
#define TC_DEF_TC_org_biocorba_seqcore_PrimarySeqList 1
static const CORBA_TypeCode anon_subtypes_array110[] =
   { (CORBA_TypeCode) &

TC_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_struct };
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_PrimarySeqList_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "PrimarySeqList",
      "IDL:org/biocorba/seqcore/PrimarySeqList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array110,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_Seq_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_Seq_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_Seq_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_Seq_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_Seq_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_Seq_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_Seq_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_Seq_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_Seq_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_Seq_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_Seq_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_Seq_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_Seq)
#define TC_DEF_TC_org_biocorba_seqcore_Seq 1
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_Seq_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "Seq", "IDL:org/biocorba/seqcore/Seq:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_1 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_3 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_4 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_6 == 'b') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_9 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_10 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_11 == '2') \
) && !defined(TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_Seq)
#define TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_Seq 1
static const CORBA_TypeCode anon_subtypes_array118[] =
   { (CORBA_TypeCode) & TC_Object_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_org_biocorba_seqcore_Seq_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array118,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_1 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_3 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_4 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_6 == 'b') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_9 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_10 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_Seq_11 == '2') \
) && !defined(TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_Seq)
#define TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_Seq 1
static const CORBA_TypeCode anon_subtypes_array127[] =
   { (CORBA_TypeCode) & TC_Object_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_org_biocorba_seqcore_Seq_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array127,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_SeqList_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqList_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqList_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqList_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqList_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqList_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqList_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqList_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqList_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqList_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqList_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqList_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_SeqList)
#define TC_DEF_TC_org_biocorba_seqcore_SeqList 1
static const CORBA_TypeCode anon_subtypes_array131[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_org_biocorba_seqcore_Seq_struct };
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_SeqList_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_alias, "SeqList", "IDL:org/biocorba/seqcore/SeqList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array131,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_FuzzyTypeCode_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_FuzzyTypeCode_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_FuzzyTypeCode_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_FuzzyTypeCode_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_FuzzyTypeCode_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_FuzzyTypeCode_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_FuzzyTypeCode_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_FuzzyTypeCode_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_FuzzyTypeCode_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_FuzzyTypeCode_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_FuzzyTypeCode_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_FuzzyTypeCode_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_FuzzyTypeCode)
#define TC_DEF_TC_org_biocorba_seqcore_FuzzyTypeCode 1
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_FuzzyTypeCode_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "FuzzyTypeCode",
      "IDL:org/biocorba/seqcore/FuzzyTypeCode:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_SeqFeaturePosition_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeaturePosition_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeaturePosition_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeaturePosition_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeaturePosition_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeaturePosition_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeaturePosition_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeaturePosition_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeaturePosition_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeaturePosition_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeaturePosition_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeaturePosition_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_SeqFeaturePosition)
#define TC_DEF_TC_org_biocorba_seqcore_SeqFeaturePosition 1
static const char *anon_subnames_array138[] =
   { "position", "extension", "fuzzy" };
static const CORBA_TypeCode anon_subtypes_array139[] =
   { (CORBA_TypeCode) & TC_CORBA_long_struct,
      (CORBA_TypeCode) & TC_CORBA_long_struct,
      (CORBA_TypeCode) & TC_CORBA_short_struct };
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_SeqFeaturePosition_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_struct, "SeqFeaturePosition",
      "IDL:org/biocorba/seqcore/SeqFeaturePosition:1.0",
   0, 3,
   (const char **) anon_subnames_array138,
   (CORBA_TypeCode *) anon_subtypes_array139,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocation_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocation_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocation_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocation_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocation_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocation_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocation_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocation_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocation_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocation_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocation_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocation_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_SeqFeatureLocation)
#define TC_DEF_TC_org_biocorba_seqcore_SeqFeatureLocation 1
static const char *anon_subnames_array142[] = { "start", "end", "strand" };
static const CORBA_TypeCode anon_subtypes_array143[] =
   { (CORBA_TypeCode) & TC_org_biocorba_seqcore_SeqFeaturePosition_struct,
      (CORBA_TypeCode) & TC_org_biocorba_seqcore_SeqFeaturePosition_struct,
      (CORBA_TypeCode) & TC_CORBA_short_struct };
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_SeqFeatureLocation_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_struct, "SeqFeatureLocation",
      "IDL:org/biocorba/seqcore/SeqFeatureLocation:1.0",
   0, 3,
   (const char **) anon_subnames_array142,
   (CORBA_TypeCode *) anon_subtypes_array143,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_1 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_3 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_4 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_6 == 'b') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_9 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_10 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_11 == '2') \
) && !defined(TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation)
#define TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation 1
static const CORBA_TypeCode anon_subtypes_array147[] =
   { (CORBA_TypeCode) & TC_org_biocorba_seqcore_SeqFeatureLocation_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array147,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_1 == 'i') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_2 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_3 == 'C') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_4 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_6 == 'b') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_7 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_8 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_9 == '0') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_10 == '_') \
&& (TC_IMPL_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_11 == '2') \
) && !defined(TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation)
#define TC_DEF_TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation 1
static const CORBA_TypeCode anon_subtypes_array156[] =
   { (CORBA_TypeCode) & TC_org_biocorba_seqcore_SeqFeatureLocation_struct };
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_sequence, NULL, NULL,
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array156,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocationList_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocationList_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocationList_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocationList_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocationList_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocationList_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocationList_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocationList_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocationList_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocationList_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocationList_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureLocationList_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_SeqFeatureLocationList)
#define TC_DEF_TC_org_biocorba_seqcore_SeqFeatureLocationList 1
static const CORBA_TypeCode anon_subtypes_array160[] =
   { (CORBA_TypeCode) &

TC_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_struct };
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_SeqFeatureLocationList_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_alias, "SeqFeatureLocationList",
      "IDL:org/biocorba/seqcore/SeqFeatureLocationList:1.0",
   0, 1,
   NULL,
   (CORBA_TypeCode *) anon_subtypes_array160,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_SeqFeature_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeature_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeature_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeature_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeature_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeature_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeature_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeature_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeature_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeature_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeature_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeature_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_SeqFeature)
#define TC_DEF_TC_org_biocorba_seqcore_SeqFeature 1
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_SeqFeature_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "SeqFeature", "IDL:org/biocorba/seqcore/SeqFeature:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqIterator_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqIterator_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqIterator_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqIterator_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqIterator_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqIterator_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqIterator_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqIterator_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqIterator_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqIterator_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqIterator_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqIterator_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_PrimarySeqIterator)
#define TC_DEF_TC_org_biocorba_seqcore_PrimarySeqIterator 1
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_PrimarySeqIterator_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "PrimarySeqIterator",
      "IDL:org/biocorba/seqcore/PrimarySeqIterator:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureIterator_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureIterator_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureIterator_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureIterator_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureIterator_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureIterator_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureIterator_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureIterator_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureIterator_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureIterator_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureIterator_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureIterator_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_SeqFeatureIterator)
#define TC_DEF_TC_org_biocorba_seqcore_SeqFeatureIterator 1
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_SeqFeatureIterator_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "SeqFeatureIterator",
      "IDL:org/biocorba/seqcore/SeqFeatureIterator:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqVector_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqVector_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqVector_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqVector_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqVector_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqVector_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqVector_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqVector_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqVector_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqVector_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqVector_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqVector_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_PrimarySeqVector)
#define TC_DEF_TC_org_biocorba_seqcore_PrimarySeqVector 1
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_PrimarySeqVector_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "PrimarySeqVector",
      "IDL:org/biocorba/seqcore/PrimarySeqVector:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureVector_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureVector_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureVector_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureVector_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureVector_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureVector_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureVector_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureVector_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureVector_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureVector_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureVector_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqFeatureVector_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_SeqFeatureVector)
#define TC_DEF_TC_org_biocorba_seqcore_SeqFeatureVector 1
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_SeqFeatureVector_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "SeqFeatureVector",
      "IDL:org/biocorba/seqcore/SeqFeatureVector:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqDB_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqDB_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqDB_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqDB_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqDB_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqDB_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqDB_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqDB_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqDB_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqDB_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqDB_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_PrimarySeqDB_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_PrimarySeqDB)
#define TC_DEF_TC_org_biocorba_seqcore_PrimarySeqDB 1
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_PrimarySeqDB_struct
   = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "PrimarySeqDB",
      "IDL:org/biocorba/seqcore/PrimarySeqDB:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_SeqDB_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqDB_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqDB_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqDB_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqDB_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqDB_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqDB_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqDB_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqDB_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqDB_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqDB_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_SeqDB_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_SeqDB)
#define TC_DEF_TC_org_biocorba_seqcore_SeqDB 1
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_SeqDB_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "SeqDB", "IDL:org/biocorba/seqcore/SeqDB:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_UpdateableSeqDB_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UpdateableSeqDB_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UpdateableSeqDB_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UpdateableSeqDB_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UpdateableSeqDB_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UpdateableSeqDB_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UpdateableSeqDB_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UpdateableSeqDB_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UpdateableSeqDB_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UpdateableSeqDB_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UpdateableSeqDB_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_UpdateableSeqDB_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_UpdateableSeqDB)
#define TC_DEF_TC_org_biocorba_seqcore_UpdateableSeqDB 1
const struct CORBA_TypeCode_struct
   TC_org_biocorba_seqcore_UpdateableSeqDB_struct = {
   {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},
   CORBA_tk_objref, "UpdateableSeqDB",
      "IDL:org/biocorba/seqcore/UpdateableSeqDB:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
#if ( (TC_IMPL_TC_org_biocorba_seqcore_BioEnv_0 == 'B') \
&& (TC_IMPL_TC_org_biocorba_seqcore_BioEnv_1 == 'i') \
&& (TC_IMPL_TC_org_biocorba_seqcore_BioEnv_2 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_BioEnv_3 == 'C') \
&& (TC_IMPL_TC_org_biocorba_seqcore_BioEnv_4 == 'o') \
&& (TC_IMPL_TC_org_biocorba_seqcore_BioEnv_5 == 'r') \
&& (TC_IMPL_TC_org_biocorba_seqcore_BioEnv_6 == 'b') \
&& (TC_IMPL_TC_org_biocorba_seqcore_BioEnv_7 == 'a') \
&& (TC_IMPL_TC_org_biocorba_seqcore_BioEnv_8 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_BioEnv_9 == '0') \
&& (TC_IMPL_TC_org_biocorba_seqcore_BioEnv_10 == '_') \
&& (TC_IMPL_TC_org_biocorba_seqcore_BioEnv_11 == '2') \
) && !defined(TC_DEF_TC_org_biocorba_seqcore_BioEnv)
#define TC_DEF_TC_org_biocorba_seqcore_BioEnv 1
const struct CORBA_TypeCode_struct TC_org_biocorba_seqcore_BioEnv_struct = {

      {{(ORBit_RootObject_Interface *) & ORBit_TypeCode_epv, TRUE, -1},
    ORBIT_PSEUDO_TYPECODE},

   CORBA_tk_objref, "BioEnv", "IDL:org/biocorba/seqcore/BioEnv:1.0",
   0, 0,
   NULL,
   NULL,
   NULL,
   CORBA_OBJECT_NIL, 0, -1, 0, 0
};
#endif
CORBA_unsigned_long GNOME_Unknown__classid = 0;

/* @func org_biocorba_seqcore_RequestTooLarge__free ***************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_RequestTooLarge__free(gpointer mem, gpointer dat,
					   CORBA_boolean free_strings)
{
   org_biocorba_seqcore_RequestTooLarge *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->reason), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}


/* @func org_biocorba_seqcore_RequestTooLarge__alloc **************************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_RequestTooLarge*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_RequestTooLarge *
org_biocorba_seqcore_RequestTooLarge__alloc(void)
{
   org_biocorba_seqcore_RequestTooLarge *retval;

   retval =
      ORBit_alloc(sizeof(org_biocorba_seqcore_RequestTooLarge),
		  (ORBit_free_childvals)
		  org_biocorba_seqcore_RequestTooLarge__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->reason), '\0', sizeof(retval->reason));
   return retval;
}


/* @func org_biocorba_seqcore_OutOfRange__free ********************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_OutOfRange__free(gpointer mem, gpointer dat,
				      CORBA_boolean free_strings)
{
   org_biocorba_seqcore_OutOfRange *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->reason), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}


/* @func org_biocorba_seqcore_OutOfRange__alloc *******************************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_OutOfRange*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_OutOfRange *
org_biocorba_seqcore_OutOfRange__alloc(void)
{
   org_biocorba_seqcore_OutOfRange *retval;

   retval =
      ORBit_alloc(sizeof(org_biocorba_seqcore_OutOfRange),
		  (ORBit_free_childvals)
		  org_biocorba_seqcore_OutOfRange__free, GUINT_TO_POINTER(1));
   memset(&(retval->reason), '\0', sizeof(retval->reason));
   return retval;
}


/* @func org_biocorba_seqcore_EndOfStream__free *******************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_EndOfStream__free(gpointer mem, gpointer dat,
				       CORBA_boolean free_strings)
{
   org_biocorba_seqcore_EndOfStream *var = mem;

   return (gpointer) (var + 1);
}


/* @func org_biocorba_seqcore_NeedsUpdate__free *******************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_NeedsUpdate__free(gpointer mem, gpointer dat,
				       CORBA_boolean free_strings)
{
   org_biocorba_seqcore_NeedsUpdate *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->reason), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}


/* @func org_biocorba_seqcore_NeedsUpdate__alloc ******************************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_NeedsUpdate*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_NeedsUpdate *
org_biocorba_seqcore_NeedsUpdate__alloc(void)
{
   org_biocorba_seqcore_NeedsUpdate *retval;

   retval =
      ORBit_alloc(sizeof(org_biocorba_seqcore_NeedsUpdate),
		  (ORBit_free_childvals)
		  org_biocorba_seqcore_NeedsUpdate__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->reason), '\0', sizeof(retval->reason));
   return retval;
}


/* @func org_biocorba_seqcore_DoesNotExist__free ******************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_DoesNotExist__free(gpointer mem, gpointer dat,
					CORBA_boolean free_strings)
{
   org_biocorba_seqcore_DoesNotExist *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->reason), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}


/* @func org_biocorba_seqcore_DoesNotExist__alloc *****************************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_DoesNotExist*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_DoesNotExist *
org_biocorba_seqcore_DoesNotExist__alloc(void)
{
   org_biocorba_seqcore_DoesNotExist *retval;

   retval =
      ORBit_alloc(sizeof(org_biocorba_seqcore_DoesNotExist),
		  (ORBit_free_childvals)
		  org_biocorba_seqcore_DoesNotExist__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->reason), '\0', sizeof(retval->reason));
   return retval;
}


/* @func org_biocorba_seqcore_UnableToProcess__free ***************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_UnableToProcess__free(gpointer mem, gpointer dat,
					   CORBA_boolean free_strings)
{
   org_biocorba_seqcore_UnableToProcess *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->reason), NULL, free_strings);
   }
   return (gpointer) (var + 1);
}


/* @func org_biocorba_seqcore_UnableToProcess__alloc **************************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_UnableToProcess*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_UnableToProcess *
org_biocorba_seqcore_UnableToProcess__alloc(void)
{
   org_biocorba_seqcore_UnableToProcess *retval;

   retval =
      ORBit_alloc(sizeof(org_biocorba_seqcore_UnableToProcess),
		  (ORBit_free_childvals)
		  org_biocorba_seqcore_UnableToProcess__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->reason), '\0', sizeof(retval->reason));
   return retval;
}

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_string_0 == 'B') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_1 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_3 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_4 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_5 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_6 == 'b') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_7 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_8 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_9 == '0') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_10 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_11 == '2') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_string)
#define ORBIT_DEF_CORBA_sequence_CORBA_string 1


/* @func CORBA_sequence_CORBA_string__free ************************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
CORBA_sequence_CORBA_string__free(gpointer mem, gpointer dat,
				  CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_string *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}


/* @func CORBA_sequence_CORBA_string__alloc ***********************************
**
** Undocumented.
**
** @return [CORBA_sequence_CORBA_string*] Undocumented
** @@
******************************************************************************/

CORBA_sequence_CORBA_string *
CORBA_sequence_CORBA_string__alloc(void)
{
   CORBA_sequence_CORBA_string *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_string),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_string__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}


/* @func CORBA_sequence_CORBA_string_allocbuf *********************************
**
** Undocumented.
**
** @param [?] len [CORBA_unsigned_long] Undocumented
** @return [CORBA_char**] Undocumented
** @@
******************************************************************************/

CORBA_char **
CORBA_sequence_CORBA_string_allocbuf(CORBA_unsigned_long len)
{
   CORBA_char **retval =
      ORBit_alloc(sizeof(CORBA_char *) * len,
		  (ORBit_free_childvals) CORBA_string__free,

		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(CORBA_char *) * len);
   return retval;
}
#endif


/* @func org_biocorba_seqcore_StringList__free ********************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_StringList__free(gpointer mem, gpointer dat,
				      CORBA_boolean free_strings)
{
   return CORBA_sequence_CORBA_string__free(mem, dat, free_strings);
}


/* @func org_biocorba_seqcore_StringList__alloc *******************************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_StringList*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_StringList *
org_biocorba_seqcore_StringList__alloc(void)
{
   return CORBA_sequence_CORBA_string__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_long_0 == 'B') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_1 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_3 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_4 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_5 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_6 == 'b') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_7 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_8 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_9 == '0') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_10 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_long_11 == '2') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_long)
#define ORBIT_DEF_CORBA_sequence_CORBA_long 1


/* @func CORBA_sequence_CORBA_long__free **************************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
CORBA_sequence_CORBA_long__free(gpointer mem, gpointer dat,
				CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_long *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}


/* @func CORBA_sequence_CORBA_long__alloc *************************************
**
** Undocumented.
**
** @return [CORBA_sequence_CORBA_long*] Undocumented
** @@
******************************************************************************/

CORBA_sequence_CORBA_long *
CORBA_sequence_CORBA_long__alloc(void)
{
   CORBA_sequence_CORBA_long *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_long),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_long__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}


/* @func CORBA_sequence_CORBA_long_allocbuf ***********************************
**
** Undocumented.
**
** @param [?] len [CORBA_unsigned_long] Undocumented
** @return [CORBA_long*] Undocumented
** @@
******************************************************************************/

CORBA_long *
CORBA_sequence_CORBA_long_allocbuf(CORBA_unsigned_long len)
{
   CORBA_long *retval =
      ORBit_alloc(sizeof(CORBA_long) * len, (ORBit_free_childvals) NULL,
		  GUINT_TO_POINTER(len));

   return retval;
}
#endif


/* @func org_biocorba_seqcore_LongList__free **********************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_LongList__free(gpointer mem, gpointer dat,
				    CORBA_boolean free_strings)
{
   return CORBA_sequence_CORBA_long__free(mem, dat, free_strings);
}


/* @func org_biocorba_seqcore_LongList__alloc *********************************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_LongList*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_LongList *
org_biocorba_seqcore_LongList__alloc(void)
{
   return CORBA_sequence_CORBA_long__alloc();
}

#if ( (ORBIT_IMPL_CORBA_sequence_CORBA_string_0 == 'B') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_1 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_3 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_4 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_5 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_6 == 'b') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_7 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_8 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_9 == '0') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_10 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_CORBA_string_11 == '2') \
) && !defined(ORBIT_DEF_CORBA_sequence_CORBA_string)
#define ORBIT_DEF_CORBA_sequence_CORBA_string 1


/* @func CORBA_sequence_CORBA_string__free ************************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
CORBA_sequence_CORBA_string__free(gpointer mem, gpointer dat,
				  CORBA_boolean free_strings)
{
   CORBA_sequence_CORBA_string *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}


/* @func CORBA_sequence_CORBA_string__alloc ***********************************
**
** Undocumented.
**
** @return [CORBA_sequence_CORBA_string*] Undocumented
** @@
******************************************************************************/

CORBA_sequence_CORBA_string *
CORBA_sequence_CORBA_string__alloc(void)
{
   CORBA_sequence_CORBA_string *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_CORBA_string),
		  (ORBit_free_childvals) CORBA_sequence_CORBA_string__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}


/* @func CORBA_sequence_CORBA_string_allocbuf *********************************
**
** Undocumented.
**
** @param [?] len [CORBA_unsigned_long] Undocumented
** @return [CORBA_char**] Undocumented
** @@
******************************************************************************/

CORBA_char **
CORBA_sequence_CORBA_string_allocbuf(CORBA_unsigned_long len)
{
   CORBA_char **retval =
      ORBit_alloc(sizeof(CORBA_char *) * len,
		  (ORBit_free_childvals) CORBA_string__free,

		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(CORBA_char *) * len);
   return retval;
}
#endif


/* @func org_biocorba_seqcore_NameValueSet__free ******************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_NameValueSet__free(gpointer mem, gpointer dat,
					CORBA_boolean free_strings)
{
   org_biocorba_seqcore_NameValueSet *var = mem;

   if (free_strings) {
      CORBA_string__free(&(var->name), NULL, free_strings);
   }
   {
      org_biocorba_seqcore_StringList__free(&(var->values), NULL,
					    free_strings);
   }
   return (gpointer) (var + 1);
}


/* @func org_biocorba_seqcore_NameValueSet__alloc *****************************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_NameValueSet*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_NameValueSet *
org_biocorba_seqcore_NameValueSet__alloc(void)
{
   org_biocorba_seqcore_NameValueSet *retval;

   retval =
      ORBit_alloc(sizeof(org_biocorba_seqcore_NameValueSet),
		  (ORBit_free_childvals)
		  org_biocorba_seqcore_NameValueSet__free,
		  GUINT_TO_POINTER(1));
   memset(&(retval->name), '\0', sizeof(retval->name));
   memset(&(retval->values), '\0', sizeof(retval->values));
   return retval;
}

#if ( (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_NameValueSet_0 == 'B') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_NameValueSet_1 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_NameValueSet_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_NameValueSet_3 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_NameValueSet_4 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_NameValueSet_5 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_NameValueSet_6 == 'b') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_NameValueSet_7 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_NameValueSet_8 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_NameValueSet_9 == '0') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_NameValueSet_10 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_NameValueSet_11 == '2') \
) && !defined(ORBIT_DEF_CORBA_sequence_org_biocorba_seqcore_NameValueSet)
#define ORBIT_DEF_CORBA_sequence_org_biocorba_seqcore_NameValueSet 1


/* @func CORBA_sequence_org_biocorba_seqcore_NameValueSet__free ***************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
CORBA_sequence_org_biocorba_seqcore_NameValueSet__free(gpointer mem,
						       gpointer dat,
						       CORBA_boolean
						       free_strings)
{
   CORBA_sequence_org_biocorba_seqcore_NameValueSet *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}


/* @func CORBA_sequence_org_biocorba_seqcore_NameValueSet__alloc **************
**
** Undocumented.
**
** @return [CORBA_sequence_org_biocorba_seqcore_NameValueSet*] Undocumented
** @@
******************************************************************************/

CORBA_sequence_org_biocorba_seqcore_NameValueSet *
CORBA_sequence_org_biocorba_seqcore_NameValueSet__alloc(void)
{
   CORBA_sequence_org_biocorba_seqcore_NameValueSet *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_org_biocorba_seqcore_NameValueSet),
		  (ORBit_free_childvals)
		  CORBA_sequence_org_biocorba_seqcore_NameValueSet__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}


/* @func CORBA_sequence_org_biocorba_seqcore_NameValueSet_allocbuf ************
**
** Undocumented.
**
** @param [?] len [CORBA_unsigned_long] Undocumented
** @return [org_biocorba_seqcore_NameValueSet*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_NameValueSet *
CORBA_sequence_org_biocorba_seqcore_NameValueSet_allocbuf(CORBA_unsigned_long
							  len)
{
   org_biocorba_seqcore_NameValueSet *retval =
      ORBit_alloc(sizeof(org_biocorba_seqcore_NameValueSet) * len,
		  (ORBit_free_childvals)
		  org_biocorba_seqcore_NameValueSet__free,

		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(org_biocorba_seqcore_NameValueSet) * len);
   return retval;
}
#endif


/* @func org_biocorba_seqcore_NameValueSetList__free **************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_NameValueSetList__free(gpointer mem, gpointer dat,
					    CORBA_boolean free_strings)
{
   return CORBA_sequence_org_biocorba_seqcore_NameValueSet__free(mem, dat,
								 free_strings);
}


/* @func org_biocorba_seqcore_NameValueSetList__alloc *************************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_NameValueSetList*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_NameValueSetList *
org_biocorba_seqcore_NameValueSetList__alloc(void)
{
   return CORBA_sequence_org_biocorba_seqcore_NameValueSet__alloc();
}

CORBA_unsigned_long org_biocorba_seqcore_SeqType__classid = 0;
CORBA_unsigned_long org_biocorba_seqcore_AnonymousSeq__classid = 0;
CORBA_unsigned_long org_biocorba_seqcore_PrimarySeq__classid = 0;

#if ( (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_0 == 'B') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_1 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_3 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_4 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_5 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_6 == 'b') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_7 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_8 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_9 == '0') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_10 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_PrimarySeq_11 == '2') \
) && !defined(ORBIT_DEF_CORBA_sequence_org_biocorba_seqcore_PrimarySeq)
#define ORBIT_DEF_CORBA_sequence_org_biocorba_seqcore_PrimarySeq 1


/* @func CORBA_sequence_org_biocorba_seqcore_PrimarySeq__free *****************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
CORBA_sequence_org_biocorba_seqcore_PrimarySeq__free(gpointer mem,
						     gpointer dat,
						     CORBA_boolean
						     free_strings)
{
   CORBA_sequence_org_biocorba_seqcore_PrimarySeq *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}


/* @func CORBA_sequence_org_biocorba_seqcore_PrimarySeq__alloc ****************
**
** Undocumented.
**
** @return [CORBA_sequence_org_biocorba_seqcore_PrimarySeq*] Undocumented
** @@
******************************************************************************/

CORBA_sequence_org_biocorba_seqcore_PrimarySeq *
CORBA_sequence_org_biocorba_seqcore_PrimarySeq__alloc(void)
{
   CORBA_sequence_org_biocorba_seqcore_PrimarySeq *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_org_biocorba_seqcore_PrimarySeq),
		  (ORBit_free_childvals)
		  CORBA_sequence_org_biocorba_seqcore_PrimarySeq__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}


/* @func CORBA_sequence_org_biocorba_seqcore_PrimarySeq_allocbuf **************
**
** Undocumented.
**
** @param [?] len [CORBA_unsigned_long] Undocumented
** @return [org_biocorba_seqcore_PrimarySeq*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_PrimarySeq *
CORBA_sequence_org_biocorba_seqcore_PrimarySeq_allocbuf(CORBA_unsigned_long
							len)
{
   org_biocorba_seqcore_PrimarySeq *retval =
      ORBit_alloc(sizeof(org_biocorba_seqcore_PrimarySeq) * len,
		  (ORBit_free_childvals)
		  org_biocorba_seqcore_PrimarySeq__free,

		  GUINT_TO_POINTER(len));
   memset(retval, '\0', sizeof(org_biocorba_seqcore_PrimarySeq) * len);
   return retval;
}
#endif


/* @func org_biocorba_seqcore_PrimarySeqList__free ****************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_PrimarySeqList__free(gpointer mem, gpointer dat,
					  CORBA_boolean free_strings)
{
   return CORBA_sequence_org_biocorba_seqcore_PrimarySeq__free(mem, dat,
							       free_strings);
}


/* @func org_biocorba_seqcore_PrimarySeqList__alloc ***************************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_PrimarySeqList*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_PrimarySeqList *
org_biocorba_seqcore_PrimarySeqList__alloc(void)
{
   return CORBA_sequence_org_biocorba_seqcore_PrimarySeq__alloc();
}

CORBA_unsigned_long org_biocorba_seqcore_Seq__classid = 0;

#if ( (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_Seq_0 == 'B') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_Seq_1 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_Seq_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_Seq_3 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_Seq_4 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_Seq_5 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_Seq_6 == 'b') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_Seq_7 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_Seq_8 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_Seq_9 == '0') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_Seq_10 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_Seq_11 == '2') \
) && !defined(ORBIT_DEF_CORBA_sequence_org_biocorba_seqcore_Seq)
#define ORBIT_DEF_CORBA_sequence_org_biocorba_seqcore_Seq 1


/* @func CORBA_sequence_org_biocorba_seqcore_Seq__free ************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
CORBA_sequence_org_biocorba_seqcore_Seq__free(gpointer mem, gpointer dat,
					      CORBA_boolean free_strings)
{
   CORBA_sequence_org_biocorba_seqcore_Seq *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}


/* @func CORBA_sequence_org_biocorba_seqcore_Seq__alloc ***********************
**
** Undocumented.
**
** @return [CORBA_sequence_org_biocorba_seqcore_Seq*] Undocumented
** @@
******************************************************************************/

CORBA_sequence_org_biocorba_seqcore_Seq *
CORBA_sequence_org_biocorba_seqcore_Seq__alloc(void)
{
   CORBA_sequence_org_biocorba_seqcore_Seq *retval;

   retval =
      ORBit_alloc(sizeof(CORBA_sequence_org_biocorba_seqcore_Seq),
		  (ORBit_free_childvals)
		  CORBA_sequence_org_biocorba_seqcore_Seq__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}


/* @func CORBA_sequence_org_biocorba_seqcore_Seq_allocbuf *********************
**
** Undocumented.
**
** @param [?] len [CORBA_unsigned_long] Undocumented
** @return [org_biocorba_seqcore_Seq*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_Seq *
CORBA_sequence_org_biocorba_seqcore_Seq_allocbuf(CORBA_unsigned_long len)
{
   org_biocorba_seqcore_Seq *retval =
      ORBit_alloc(sizeof(org_biocorba_seqcore_Seq) * len,
		  (ORBit_free_childvals) org_biocorba_seqcore_Seq__free,
		  GUINT_TO_POINTER(len));

   memset(retval, '\0', sizeof(org_biocorba_seqcore_Seq) * len);
   return retval;
}
#endif


/* @func org_biocorba_seqcore_SeqList__free ***********************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_SeqList__free(gpointer mem, gpointer dat,
				   CORBA_boolean free_strings)
{
   return CORBA_sequence_org_biocorba_seqcore_Seq__free(mem, dat,
							free_strings);
}


/* @func org_biocorba_seqcore_SeqList__alloc **********************************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_SeqList*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_SeqList *
org_biocorba_seqcore_SeqList__alloc(void)
{
   return CORBA_sequence_org_biocorba_seqcore_Seq__alloc();
}

CORBA_unsigned_long org_biocorba_seqcore_FuzzyTypeCode__classid = 0;

/* @func org_biocorba_seqcore_SeqFeaturePosition__free ************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_SeqFeaturePosition__free(gpointer mem, gpointer dat,
					      CORBA_boolean free_strings)
{
   org_biocorba_seqcore_SeqFeaturePosition *var = mem;

   return (gpointer) (var + 1);
}


/* @func org_biocorba_seqcore_SeqFeaturePosition__alloc ***********************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_SeqFeaturePosition*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_SeqFeaturePosition *
org_biocorba_seqcore_SeqFeaturePosition__alloc(void)
{
   org_biocorba_seqcore_SeqFeaturePosition *retval;

   retval =
      ORBit_alloc(sizeof(org_biocorba_seqcore_SeqFeaturePosition),
		  (ORBit_free_childvals)
		  org_biocorba_seqcore_SeqFeaturePosition__free,
		  GUINT_TO_POINTER(1));
   return retval;
}


/* @func org_biocorba_seqcore_SeqFeatureLocation__free ************************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_SeqFeatureLocation__free(gpointer mem, gpointer dat,
					      CORBA_boolean free_strings)
{
   org_biocorba_seqcore_SeqFeatureLocation *var = mem;

   return (gpointer) (var + 1);
}


/* @func org_biocorba_seqcore_SeqFeatureLocation__alloc ***********************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_SeqFeatureLocation*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_SeqFeatureLocation *
org_biocorba_seqcore_SeqFeatureLocation__alloc(void)
{
   org_biocorba_seqcore_SeqFeatureLocation *retval;

   retval =
      ORBit_alloc(sizeof(org_biocorba_seqcore_SeqFeatureLocation),
		  (ORBit_free_childvals)
		  org_biocorba_seqcore_SeqFeatureLocation__free,
		  GUINT_TO_POINTER(1));
   return retval;
}

#if ( (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_0 == 'B') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_1 == 'i') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_2 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_3 == 'C') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_4 == 'o') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_5 == 'r') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_6 == 'b') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_7 == 'a') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_8 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_9 == '0') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_10 == '_') \
&& (ORBIT_IMPL_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_11 == '2') \
) && !defined(ORBIT_DEF_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation)
#define ORBIT_DEF_CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation 1


/* @func CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation__free *********
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation__free(gpointer mem,
							     gpointer dat,
							     CORBA_boolean
							     free_strings)
{
   CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation *val = mem;

   if (val->_release)
      ORBit_free(val->_buffer, free_strings);
   return (gpointer) (val + 1);
}


/* @func CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation__alloc ********
**
** Undocumented.
**
** @return [CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation*] Undocumented
** @@
******************************************************************************/

CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation *
CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation__alloc(void)
{
   CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation *retval;

   retval =
      ORBit_alloc(sizeof
		  (CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation),
		  (ORBit_free_childvals)
		  CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation__free,
		  GUINT_TO_POINTER(1));
   retval->_maximum = 0;
   retval->_length = 0;
   retval->_buffer = NULL;
   retval->_release = CORBA_FALSE;
   return retval;
}


/* @func CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_allocbuf ******
**
** Undocumented.
**
** @param [?] len [CORBA_unsigned_long] Undocumented
** @return [org_biocorba_seqcore_SeqFeatureLocation*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_SeqFeatureLocation *
CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation_allocbuf
   (CORBA_unsigned_long len)
{
   org_biocorba_seqcore_SeqFeatureLocation *retval =
      ORBit_alloc(sizeof(org_biocorba_seqcore_SeqFeatureLocation) * len,
		  (ORBit_free_childvals) NULL, GUINT_TO_POINTER(len));

   return retval;
}
#endif


/* @func org_biocorba_seqcore_SeqFeatureLocationList__free ********************
**
** Undocumented.
**
** @param [?] mem [gpointer] Undocumented
** @param [?] dat [gpointer] Undocumented
** @param [?] free_strings [CORBA_boolean] Undocumented
** @return [gpointer] Undocumented
** @@
******************************************************************************/

gpointer
org_biocorba_seqcore_SeqFeatureLocationList__free(gpointer mem, gpointer dat,
						  CORBA_boolean free_strings)
{
   return CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation__free(mem,
								       dat,
								       free_strings);
}


/* @func org_biocorba_seqcore_SeqFeatureLocationList__alloc *******************
**
** Undocumented.
**
** @return [org_biocorba_seqcore_SeqFeatureLocationList*] Undocumented
** @@
******************************************************************************/

org_biocorba_seqcore_SeqFeatureLocationList *
org_biocorba_seqcore_SeqFeatureLocationList__alloc(void)
{
   return CORBA_sequence_org_biocorba_seqcore_SeqFeatureLocation__alloc();
}

CORBA_unsigned_long org_biocorba_seqcore_SeqFeature__classid = 0;
CORBA_unsigned_long org_biocorba_seqcore_PrimarySeqIterator__classid = 0;
CORBA_unsigned_long org_biocorba_seqcore_SeqFeatureIterator__classid = 0;
CORBA_unsigned_long org_biocorba_seqcore_PrimarySeqVector__classid = 0;
CORBA_unsigned_long org_biocorba_seqcore_SeqFeatureVector__classid = 0;
CORBA_unsigned_long org_biocorba_seqcore_PrimarySeqDB__classid = 0;
CORBA_unsigned_long org_biocorba_seqcore_SeqDB__classid = 0;
CORBA_unsigned_long org_biocorba_seqcore_UpdateableSeqDB__classid = 0;
CORBA_unsigned_long org_biocorba_seqcore_BioEnv__classid = 0;
#endif
